spring:
  profiles:
    active: local
    group:
      local:
        - properties-local
      develop:
        - properties-develop

server:
  port: 8080
  servlet:
      context-path: /eegoba

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: lgcns.eegoba.api.**.vo

logging:
  config: classpath:log4j2/log4j2.xml
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-eegoba-free.cj51oedluw3v.us-east-1.rds.amazonaws.com:3306/eegoba
    username: admin
    password: asdf1234!

---
#spring:
#  config:
#    activate:
#      on-profile: develop
#  datasource:
    # MYSQL
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username:
#    password:
